### ISSUE TITLE
Will it get siblings if the parent is null?

### ISSUE THREAD

**Issue by SyedMSawaid** [1and1/acts_as_recursive_tree#28]
Suppose I want to scope all `Todo` by a `Project`. So if all the `Todo`s don't have a parent aka it is `nil`, then how do I get its siblings without breaking out of its scope?

**Comment by wollistik** [comment]
Hi, there is already the `roots` scope presents (which is actually a nil check). So if I understand you correctly, you have some models that look more or less like this:
```ruby
class Project < ApplicationRecord
  has_many :todos
end

class Todo < ApplicationRecord
  belongs_to :project
  acts_as_recursive_tree
end
```

And now you want only the root Todos of a project:


```ruby
project.todos.roots
```

Did this help? Otherwise please give a more detailed setup of what you want to achieve.

**Comment by SyedMSawaid** [comment]
Oh. got it. Thanks btw.
