### ISSUE TITLE
Is there an option for recursive deletion?

### ISSUE THREAD

**Issue by SyedMSawaid** [1and1/acts_as_recursive_tree#31]
Like suppose if I delete the parent, I want all its children to be deleted.

**Comment by wollistik** [comment]
:thinking: This is a good point - in our application we have a database-constraint to delete all child nodes, but this should be done/configurable via the `dependent` option on the children-association. I will think about this and prepare an PR as soon as I have some spare time. Which might be not too soon, because there is quite a lot of urgent stuff at work :disappointed: .

**Comment by SyedMSawaid** [comment]
For now, I did it with `before_delete` callback. I will take a look at the source code and see if I can do that.
I will create a PR if I write the code for it.
